moogar0880/PyTrakt

- trakt/core.py
The base url for the Trakt.tv API has been changed. See http://docs.trakt.apiary.io/#introduction/api-url.
> Updated BASE_URL to correct url

- trakt/calendar.py
when getting any kind of calendar the order of season # and episode # was flipped in the _build function
> fixed the order of episode and season since they were flipped

- trakt/tv.py
Various IDs were not correctly imported for TVShow (named "trakt_id" instead of "trakt", so _build did not work)
> Fixed IDs for TVShow

- trakt/calendar.py
Use "ids" instead of "episode_ids" as `utils.extract_ids` expects "ids" key.
> Fixed missing episode ids returned from calendar

- trakt/core.py
- trakt/errors.py
Added two functions that will allow you get a device_code and check for a successful oauth authentication.
Added one function that you can use to authenticate named device_auth.
Docs:
https://trakt.docs.apiary.io/#reference/authentication-devices/device-code/poll-for-the-access_token
https://trakt.docs.apiary.io/#reference/authentication-devices/get-token/poll-for-the-access_token
I've separated these, as the method to authenticate polls for the authentication (poll-for-the-access_token). And some applications (as ours) would rather not have this block any other processes.
I do have a few remarks regarding the code.
The existing authentication methods are not storing the REFRESH_TOKEN. Meaning that after three months you'll have to go through the same process. I've started adding it to …
> Added trakt oauth device authentication.

- trakt/core.py
when loading config file, module crash because OAUTH_REFRESH is not in config file. the key is not needed when doing PIN authentication
> fix usging PIN_AUTH with stored auth keys

- trakt/core.py
Here `response.__bool__` is actually a shortcut for `response.ok`:
```python
if response and response.status_code == 400:
raise errors.BadRequestException(error.message)
```
As a result of this `get_device_token` throws `JSONDecodeError`, when trakt api responds with the pending status code.
Anyway I've decided to rewrite the code to return `Response` instead of json, the user can always call `response.json()` themselves, but this way they also get to know the status code and decide exactly what to do with it.
> Fixed device authentication

- CONTRIBUTORS.md
- trakt/core.py
To have `oauth_auth` perform the token exchange seemed like the cleanest option.
Tell me if you want anything changed.
> split oauth terminal to add some automation ability

- CONTRIBUTORS.md
- trakt/tv.py
Expose the [next](https://trakt.docs.apiary.io/#reference/shows/next-episode/get-next-episode) / [last](https://trakt.docs.apiary.io/#reference/shows/next-episode/get-last-episode) episode API endpoints in the `TVShow` class as properties.
> Add next/last episode endpoint to `TVShow`

- trakt/errors.py
As per the python [exceptions](https://docs.python.org/3/library/exceptions.html) docs, TraktException should inherit from Exception instead of BaseException.
This change fixes the HomeAssistant custom component so it doesn't kill HomeAssistant (all user code should expect Exception, nothing will catch TraktException if it's BaseException...)
Unfortunately I don't have a devenv set up, so couldn't test it, but I've found no other code depending on BaseException.
> TraktException should inherit from Exception

- trakt/core.py
It is possible to use Trakt API to refresh access token automatically using `refresh_token`. This PR adds a function to do so.
It checks if OAuth access token has not expired, and request a new one if needed.
Trakt access token are valid only [during 3 months](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token).
closes #117 
closes https://github.com/Taxel/PlexTraktSync/issues/20
> Automatically refresh token after expiration

- tests/mock_data/users.json
- trakt/users.py
This removes the "user" entry from the API dict for `/users/[slug]/lists` so that it will properly
be replaced with the User self object. Fixes #113
> User lists

- trakt/sync.py
Previously queries to the various trakt search APIs were slugified which
made it impossible to query for certain items when those items contained
punctuation not allowed in trakt slugs.
This change changes the behavior of the search APIs to ensure that
queries are left intact unless specifically requested that they be
slugified by providing the slugify=True option to the search API.
Closes #116
> Ensure search queries are left unaltered

- trakt/users.py
Trakt API need requests to use the username in its slug version. Username may contain special characters such as spaces that are not allowed in URI.
This PR make requests use slugified `username`.
fixes #126
> Slugify username for URI

- trakt/core.py
- trakt/errors.py
To be able to read the "Retry-After" value of a 429 http error ([trakt rate limit](https://trakt.docs.apiary.io/#introduction/rate-limiting) exceeded) the rised exception should give access to http response header.
This PR adds the http response to TraktException.
> Add http response to TraktException

- trakt/errors.py
I was debugging `ValueError` being thrown from `search_by_id`, which appeared to be `JSONDecodeError` (`JSONDecodeError` is subclass of `ValueError`) happening on decode of empty response (`''`).
```python
search = trakt.sync.search_by_id('264991/2/2', id_type='tvdb')
```
> Add MethodNotAllowedException exception for 405 status code

- Makefile
Using pip (typically python2) would yield error like:
```
pkg_resources.DistributionNotFound: The 'pip==19.3.1' distribution was not found and is required by the application
```
> Use python3 when using pip

- trakt/core.py
- trakt/sync.py
- trakt/utils.py
I noticed when I called `trakt.sync.add_to_history(movie)` (or `tv`), the time on trakt.tv was getting set in the past (the number of hours my current timezone is offset from GMT / UTC). Updated the defaults to use timezone-aware datetime logic. Timezone handling is confusing so I used [this as a reference](https://blog.ganssle.io/articles/2019/11/utcnow.html).
[Current utils code](https://github.com/moogar0880/PyTrakt/blob/2.14.1-release/trakt/utils.py#L27-L36) also drops timezone info for `airs_date`, but I couldn't figure out an elegant way to fix that.
Changes:
- update for `.now()` with `datetime.timezone` with timezone-aware datetimes
- change `utcnow() -> now(tz=timezone.utc)`
- change `utcfromtimestamp(...) -> fromtimestamp(..., tz=timezone.utc)`
- use `strftime` directly for …
> Update datetime.now calls to use timezone info

- trakt/core.py
The intent is to be able to override in client libraries with requests_cache for example:
- https://github.com/reclosedev/requests-cache/issues/289
----
```py
trakt.core.session = CachedSession()
trakt.init(client_id=client_id, client_secret=client_secret, store=True)
```
> Add global session object for requests

- trakt/core.py
This PR fixes a mispelled info log message.
Error :
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
msg = self.format(record)
File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
return fmt.format(record)
File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
record.message = record.getMessage()
File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File "/usr/local/lib/python3.9/site-packages/trakt/users.py", line 5, in <module>
from trakt.movies import Movie
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen …
```
> Fix "token refreshed" log message

- trakt/errors.py
Similarly to https://github.com/moogar0880/PyTrakt/pull/141 add new LockedUserAccountException exception for HTTP code 423.
See https://github.com/Taxel/PlexTraktSync/issues/579#issuecomment-962427562
And https://github.com/trakt/api-help/issues/228
> Add LockedUserAccountException (HTTP code 423)

- tests/conftest.py
PyCharm runs the tests from the directory the test itself resides.
> Fix/Tests: Allow running tests from arbitary working dir
