moogar0880/PyTrakt

- trakt/__init__.py
- trakt/_core.py
Quick fix for api response processing errors. Will eventually need to port this lib to using V2 of the trakt api
> API Response Fixes

- HISTORY.rst
- trakt/__init__.py
- trakt/errors.py
- trakt/tv.py
- trakt/utils.py
* Fixes Generator issue detailed in #7
* Fixes Python 2x Unicode bug
> Python 2x Compatibility Fix

- trakt/__init__.py
- trakt/utils.py
Bug fix for the TVShow `first_aired` date parsing issue discovered while investigating #9
> TVShow First Aired Bug Fix

- HISTORY.rst
- trakt/__init__.py
- trakt/core.py
- trakt/errors.py
- trakt/tv.py
* Fixed TVEpisode Scrobbling Bug (#13)
* Fixed DEBUG logging messages to properly reflect HTTP Methods
* Added a 400 HTTP Response Code Exception type
> Episode Scrobbling Fix

- trakt/movies.py
- trakt/people.py
- trakt/tv.py
Adds default values to some `dict.get` calls that aren't critical to the objects being built.
Also updated some docstrings
> Add default values for non-critical response keys

- trakt/core.py
since using input on python 2 requires the user to input a quote mark before and after pin/client key/ client secret
> added python 2 raw_input statments

- trakt/users.py
Allows you to get the default watch list of users, both movies, and shows.
> Added to User watchlist_shows and watchlist_movies

- .gitignore
- tests/SearchTests.py
- trakt/sync.py
Added ID lookup, so it's possible to search by remote ID's like IMDB.
> Added search by ID

- HISTORY.rst
- docs/getstarted.rst
- trakt/__init__.py
- trakt/core.py
- trakt/users.py
* Cleaned up some ugliness in the auth workflows
* User GET's now actually fetch User data from trakt
* User.watching no longer raises an exception if a user isn't watching anything (#40)
* HTTP 204 responses now return None for more obvious error handling
> Handle 204

- HISTORY.rst
- trakt/__init__.py
- trakt/users.py
Fixes return from generator py 2.x bug (#45)
> 2.4.1 Updates

- HISTORY.rst
- trakt/__init__.py
- trakt/core.py
Fix authentication issue pointed out by @BrendanBall (#48)
> trakt-api-key Fixes

- .landscape.yaml
- .travis.yml
- HISTORY.rst
- Makefile
- README.rst
- testing-requirements.txt
- tests/test_utils.py
- trakt/__init__.py
- trakt/utils.py
Fixes #51 
Adds correct unicode character escaping and correct non-word character replacements
> Updates to Slugify Function

- .landscape.yaml
- HISTORY.rst
- requirements.txt
- trakt/__init__.py
- trakt/calendar.py
- trakt/core.py
- trakt/errors.py
- trakt/users.py
- trakt/utils.py
* Add `six` support for cleaner 2-3 compatability
* General code cleanup and style improvements
> Add Six Support

- trakt/core.py
Added some parentheses in the _bootstrapped if statement so the comparison works as intended.
> Update _bootstrapped comparison

- HISTORY.rst
- trakt/__init__.py
- trakt/core.py
- trakt/errors.py
- trakt/movies.py
- trakt/people.py
- trakt/sync.py
- trakt/tv.py
- trakt/utils.py
Fix and clean up `__all__` exports across `trakt` submodules
Closes #70
> Clean Up Module Exports

- tests/mock_data/comments.json
- tests/mock_data/episodes.json
- tests/mock_data/movies.json
- tests/mock_data/seasons.json
- tests/mock_data/shows.json
- trakt/core.py
- trakt/tv.py
TypeError: **new**() got an unexpected keyword argument 'likes'
> fix comments broken

- trakt/utils.py
https://api-v2launch.trakt.tv/shows/impulse?extended=full
> fix the case in which first_aired property of tv show is null

- HISTORY.rst
- trakt/__init__.py
> update changelog for 2.8.3

- HISTORY.rst
- trakt/__init__.py
> 2.13.0 release docs

- docs/index.rst
- docs/sync.rst
- tests/conftest.py
- tests/mock_data/recommendations.json
- tests/mock_data/shows.json
- tests/test_shows.py
- tests/test_sync.py
- trakt/calendar.py
- trakt/core.py
- trakt/people.py
- trakt/sync.py
- trakt/tv.py
Changes listed in the comments
I still need to double check I didn't leave anything out. Have to compare to the branch i've been working on.
> Multiple changes

- tests/conftest.py
refs:
- https://github.com/moogar0880/PyTrakt/pull/137
- https://github.com/moogar0880/PyTrakt/pull/142
> tests/conftest.py: Remove Python2 compatibility

- tests/conftest.py
- tests/test_episodes.py
- tests/test_search.py
- tests/test_users.py
- trakt/movies.py
- trakt/tv.py
Used https://pythonrepo.com/repo/myint-autoflake-python-code-refactoring
but since that didn't cleanup all, cleaned up some others manually.
> Chore: Code cleanups

- trakt/core.py
Fixes https://github.com/moogar0880/PyTrakt/issues/150
> Refactor: Do config loading (bootstrap) at runtime rather module load time
